// flow-typed signature: a440d5fd2629938541ccf49b5cd03c4b
// flow-typed version: <<STUB>>/countup.js_v^1.8.5/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'countup.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'countup.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'countup.js/countUp-jquery' {
  declare module.exports: any;
}

declare module 'countup.js/countUp' {
  declare module.exports: any;
}

declare module 'countup.js/demo' {
  declare module.exports: any;
}

declare module 'countup.js/dist/countUp' {
  declare module.exports: any;
}

declare module 'countup.js/dist/countUp.min' {
  declare module.exports: any;
}

declare module 'countup.js/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'countup.js/countUp-jquery.js' {
  declare module.exports: $Exports<'countup.js/countUp-jquery'>;
}
declare module 'countup.js/countUp.js' {
  declare module.exports: $Exports<'countup.js/countUp'>;
}
declare module 'countup.js/demo.js' {
  declare module.exports: $Exports<'countup.js/demo'>;
}
declare module 'countup.js/dist/countUp.js' {
  declare module.exports: $Exports<'countup.js/dist/countUp'>;
}
declare module 'countup.js/dist/countUp.min.js' {
  declare module.exports: $Exports<'countup.js/dist/countUp.min'>;
}
declare module 'countup.js/gulpfile.js' {
  declare module.exports: $Exports<'countup.js/gulpfile'>;
}
